name: OHMySQL
options:
  bundleIdPrefix: com.ohmysql.apple
settings:
  configs:
    debug:
      OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella
    release:
      OTHER_SWIFT_FLAGS: -Wno-incomplete-umbrella

targets:
  OHMySQL:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: [OHMySQL/Sources]
    scheme: {}
    settings:
      configs:
        debug:
          GENERATE_INFOPLIST_FILE: YES
        release:
          GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd

  OHMySQL-macOS:
    type: framework
    platform: macOS
    deploymentTarget: "11.0"
    sources: [OHMySQL/Sources]
    scheme: {}
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd

  OHMySQL-watchOS:
    type: framework
    platform: watchOS
    deploymentTarget: "8.0"
    sources: [OHMySQL/Sources]
    scheme: {}
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd

  OHMySQL-tvOS:
    type: framework
    platform: tvOS
    deploymentTarget: "15.0"
    sources: [OHMySQL/Sources]
    scheme: {}
    dependencies:
      - framework: OHMySQL/lib/MySQL.xcframework
      - sdk: Foundation.framework
      - sdk: libc++.tbd
