name: MySQL iOS

on:
  push:
    branches: [ master, develop ]

jobs:
  Generate:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'
    - name: Generate archive
      run: |
        xcodebuild docbuild -scheme 'OHMySQL' -derivedDataPath ./build -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13'
    - name: Generate pages
      run: |
        $(xcrun --find docc) process-archive transform-for-static-hosting ./build/Build/Products/Debug-iphonesimulator/OHMySQL.doccarchive --hosting-base-path OHMySQL --output-path ./docs
    - name: Deploy documentation to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: true